# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Increment the Version Code"
  lane :increment_version_code do
    increment_version_code(
        gradle_file_path: './app/build.gradle'
    )

    git_commit(
      path: ["./app/build.gradle"],
      message: "RELEASE INCREMENT VERSION CODE"
    )

    push_to_git_remote
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    increment_version_code

    gradle(
        task: 'bundle',
        flavor: "live",
        build_type: 'Release',
        properties: {
                "android.injected.signing.store.file" => "#{ENV["KEYSTORE_FILE"]}",
                "android.injected.signing.store.password" => "#{ENV["KEYSTORE_PASSWORD"]}",
                "android.injected.signing.key.alias" => "#{ENV["KEYSTORE_KEY_ALIAS"]}",
                "android.injected.signing.key.password" => "#{ENV["KEYSTORE_KEY_PASSWORD"]}",
              },
    )
    upload_to_play_store
  end
end
