name: Android CI

on:
  push:
    branches:
      - 'release/release'
      - 'feature/moneymong-500-ci-cd-구축'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create API Certificate
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties
        echo "native_app_key=\"${{ secrets.NATIVE_APP_KEY }}\"" >> ./local.properties
        echo "CLOVA_OCR_DOCUMENT_SECRET=\"${{ secrets.CLOVA_OCR_DOCUMENT_SECRET }}\"" >> ./local.properties
        echo "CLOVA_OCR_DOCUMENT_BASEURL=\"${{ secrets.CLOVA_OCR_DOCUMENT_BASEURL }}\"" >> ./local.properties

    - name: Clean Build
      run: ./gradlew clean

    - name: Decode Service Account Key
      env:
        SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $SERVICE_ACCOUNT_KEY_BASE64 | base64 --decode > service_account_key.json

    - name: Decode Keystore File
      env:
        KEY_STORE_BASE64: ${{ secrets.KEYSTORE_FILE }}
      run: |
        echo $KEY_STORE_BASE64 | base64 --decode > moneymong_keystore.keystore

    - name: Build & Deploy Android release
      env:
        SERVICE_ACCOUNT_KEY: service_account_key.json
        KEYSTORE_FILE: moneymong_keystore.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: bundle exec fastlane deploy

    - name: Remove Credential
      run: rm service_account_key.json moneymong_keystore.keystore local.properties
