name: Android CI

on:
  push:
    branches:
      - 'release/release'
      - 'feature/moneymong-500-ci-cd-구축'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create API Certificate
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties
        echo "native_app_key=\"${{ secrets.NATIVE_APP_KEY }}\"" >> ./local.properties
        echo "CLOVA_OCR_DOCUMENT_SECRET=\"${{ secrets.CLOVA_OCR_DOCUMENT_SECRET }}\"" >> ./local.properties
        echo "CLOVA_OCR_DOCUMENT_BASEURL=\"${{ secrets.CLOVA_OCR_DOCUMENT_BASEURL }}\"" >> ./local.properties

    - name: Clean Build
      run: ./gradlew clean

    - name: Decode Service Account Key
      run: |
        echo "${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}" | base64 --decode > ./app/service_account_key.json

    - name: Decode Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ./app/moneymong_keystore.jks

    - name: Build & Deploy Android release
      env:
        SERVICE_ACCOUNT_KEY: ./app/service_account_key.json
        KEYSTORE_FILE: ./app/moneymong_keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        CWD: ${{ github.workspace }}
      run: bundle exec fastlane deploy

    - name: Remove Credential
      run: rm ./app/${SERVICE_ACCOUNT_KEY} && rm ./app/${KEYSTORE_FILE} && rm ./local.properties
